version: "3"

services:
  db:
    image: postgres
    #restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    #restart: always
    ports:
      - 8080:8080

  backend:
    build: ./backend
    volumes:
      - type: bind
        source: ./backend/src
        target: /code/src
    ports:
      - "8000:80"

  frontend:
    build: ./frontend
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - ${PORT}:${PORT}
    command: npm run dev
    develop:
      watch:
        - action: rebuild
          path: ./frontend/src
          target: /usr/src/app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    #depends_on:
    #  - backend
    #  - db

volumes:
  pgdata:
