version: "3"

services:
  backend:
    build: ./backend
    volumes:
      - type: bind
        source: ./backend/src
        target: /code/src
    ports:
      - "8000:80"

  db:
    image: postgres
    #restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"

  adminer:
    image: adminer
    #restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
